version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    CLUSTER_NAME: rollback-cluster
    DEPLOYMENT_NAME: rollback-dep
    CONTAINER_NAME: my-rollback-container
    REPOSITORY_URI: 466749146115.dkr.ecr.ap-south-1.amazonaws.com/sridhar-repo
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

  build:
    commands:
      - echo "Updating Kubernetes Deployment..."
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Checking rollout status..."
      - |
        if kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=180s; then
          echo "Deployment Successful"
        else
          echo "Deployment Failed"
          kubectl rollout undo deployment/$DEPLOYMENT_NAME
          exit 1
        fi

