---
version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ACCOUNT_ID: "466749146115"
    ECR_REPOSITORY: sridhar-repo
    CLUSTER_NAME: sridhar-Dep
    DEPLOYMENT_NAME: rollback-dep
    CONTAINER_NAME: my-rollback-container
    IMAGE_TAG: v3

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
      - >-
        aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t rollback:v3 .
      - docker tag rollback:v3 $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Image"
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo "Deploying to EKS"
      - >-
        aws eks update-kubeconfig --region $AWS_REGION
        --name $CLUSTER_NAME

      - >-
        sed -i "s|IMAGE_PLACEHOLDER|$REPOSITORY_URI:$IMAGE_TAG|g"
        deployment.yaml

      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

      - echo "Checking Deployment"
      - >-
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        --timeout=120s ||
        kubectl rollout undo deployment/$DEPLOYMENT_NAME
