apiVersion: apps/v1
kind: Deployment

metadata:
  name: rollback-dep

spec:
  replicas: 3

  selector:
    matchLabels:
      app: rollback-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: rollback-app

    spec:
      containers:
      - name: my-rollback-container
        image: 466749146115.dkr.ecr.ap-south-1.amazonaws.com/sridhar-repo:1
        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
