apiVersion: v1
kind: Service

metadata:
  name: rollback-service

spec:

  selector:
    app: rollback-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollback-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:466749146115:certificate/e1084710-c035-423c-aa18-cc2463e24dac
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"

spec:
  ingressClassName: alb

  rules:
  - host: k8.securelab.link
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollback-service
            port:
              number: 80
      
